apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\micha\source\repos\MS.Paint2\Paint\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
  - name: "12000"
    port: 12000
    targetPort: 27017
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
